### ISSUE TITLE
Move expiration moment calculation out of ETS backend

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-cache#1]
Currently `rabbit_auth_cache_ets:expiration/1` is used to calculate key expiration. Should this be moved out of a backend? Is the idea that some backends would prefer using a different algorithm altogether, e.g. LRU?

This is a question more than something I perceive as an issue.

**Comment by michaelklishin** [comment]
`rabbit_auth_cache_ets_segmented:expiration/1` does exactly the same thing, so looks like it can be extracted already.

**Comment by hairyhum** [comment]
What do you mean by "moved out of backend"?
Backend API right now is requiring `put(Key, Value, TTL)`, while expiration is internal for backend.
It can (and should) be moved out from `gen_server` process though.

**Comment by michaelklishin** [comment]
TTL calculation should not be done by backends because it probably won't
differ from backend to backend.

On Wed, Jun 1, 2016 at 3:35 PM, Daniil Fedotov notifications@github.com
wrote:

> What do you mean by "moved out of backend"?
> Backend API right now is requiring put(Key, Value, TTL), while expiration
> is internal for backend.
> It can (and should) be moved out from gen_server process though.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/rabbitmq/rabbitmq-auth-backend-cache/issues/1#issuecomment-222978961,
> or mute the thread
> https://github.com/notifications/unsubscribe/AAAEQoakpoOjKVH7wucY2wRq9oPU7kobks5qHXyigaJpZM4IrDDt
> .

## 

MK

Staff Software Engineer, Pivotal/RabbitMQ

**Comment by hairyhum** [comment]
We can move `expiration` and `expired` functions to `rabbit_auth_cache`, just to avoid duplication. We have to transform TTL to expiration or vice versa anyway.

**Comment by michaelklishin** [comment]
@hairyhum good idea.

**Comment by hairyhum** [comment]
Done in `stable` and `master`
